template = "https://github.com/giellalt/template-lang-und"
rev_id = 335
template_sha = "656172fb5ca68a68ee8547c7bc0cd1ce3f605fd7"

[replacements]
__GLOTTOLOG_ID__ = "cent2127"
__REPO__ = "lang-esu"
__UND2C__ = "esu"
__UNDEFINED__ = "Central Yupik"
__UND__ = "esu"
