template = "https://github.com/giellalt/template-lang-und"
rev_id = 336
template_sha = "389e4bc166fb75b7405a9d137e775aeee3aae1fb"

[replacements]
__GLOTTOLOG_ID__ = "cent2127"
__REPO__ = "lang-esu"
__UND2C__ = "esu"
__UNDEFINED__ = "Central Yupik"
__UND__ = "esu"
