template = "https://github.com/giellalt/template-lang-und"
rev_id = 346
template_sha = "f98c2a37b9866895a157f22bea282f596e7a321a"

[replacements]
__GLOTTOLOG_ID__ = "cent2127"
__REPO__ = "lang-esu"
__UND2C__ = "esu"
__UNDEFINED__ = "Central Yupik"
__UND__ = "esu"
