[package]
name = "esu"
human_name = "Central Yupik"
version = "4.2.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.esu]
filename = "esu-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-esu"
platform = "windows"
uuid = "60A7E62E-9E4E-11EA-9DCC-FB846BA46895"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.esu"
package = "speller-esu"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-esu-mso"
platform = "windows"
uuid = "6DDA6B00-9E4E-11EA-9465-87DB239B8845"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-esu"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
